spring:
  datasource:
    url: jdbc:${DBMS}://${DB_HOST}:${DB_PORT}/mwoyeottheora?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    show-sql: false
    format-sql: false
    highlight-sql: false
    ddl-auto: ${DDL_AUTO_MODE}
    pool-size: 50
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul

server:
  shutdown: graceful
  port: 8090

jwt:
  accessTokenExpirationForMinute: 7200
  jwtHeaderName: Authorization
  jwtTokenType: Bearer
  secretKey: asdfasdf
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    show-sql: true
    format-sql: true
    highlight-sql: true